language: r
cache: packages
pandoc_version: 2.10

before_install:
  ## cf <https://travis-ci.community/t/pandoc-lualatex-font-error/9409/4>
  - tlmgr update --all || true     # one package fails to update but that doesn't affect the outcome
  - tlmgr install unicode-math lualatex-math pdftexcmds infwarerr luaotfload
  - luaotfload-tool --update

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
