# Software, hardware, and accounts #

- [R](https://cran.r-project.org/) and [RStudio](https://rstudio.com/products/rstudio/download/):  
    - Last year R had a major release (version 4)
    - Addressing some bugs has led to some rapid development in R and RStudio
    - For consistency in class, **please use the latest version of both R and RStudio**
    - [Help on switching between different versions of R](https://support.rstudio.com/hc/en-us/articles/200486138-Changing-R-versions-for-the-RStudio-Desktop-IDE)
    
- OS:  
    - All of the tools we'll use are available on all major OSes
    - I have much less experience debugging Windows and Linux, but will do what I can
    
- You'll need a [GitHub](https://github.com/) account
    - GitHub is [owned by Microsoft](https://www.cnbc.com/2020/11/29/microsofts-github-has-become-magnet-for-thorny-issues-like-riaa.html)
    - And there are [concerns about how it mined public repositories to develop a code completion tool](https://www.theverge.com/2021/7/7/22561180/github-copilot-legal-copyright-fair-use-public-code)
    - But it offers some key features that I want to use in this course
    - You can do everything this course requires in private repositories, so long as you give access to the people who need access

- I strongly recommend *against* tablets (iPad, Surface) for this course
    - Unless you're using a cloud service such as RStudio Cloud

- I recommend that your machine have at least
    - 200 GB free hard drive space
    - 8 GB RAM
    - Intel i5 processor
    - Operating system capable of running the most recent release of R (4.1.0 as of 2021-07-28)
        - Mac: 10.13 (High Sierra) or more recent
        - Windows: See [here](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Does-R-run-under-Windows-Vista_003f)
        - If you're running Linux I'm going to assume you can figure this out yourself

## A Note on Accessibility ##

I chose the tools and platforms for this course in part because they're industry-standard.  If you pursue a career as a data scientist in industry, you'll be expected to use Slack and GitHub on a daily basis.  And RStudio is by far the most commonly used IDE ("integrated development environment") for R.  

However, like many other technologies, they were originally developed using ableist assumptions about "normal" computer users.  In response to criticism, the developers of these systems and tools have gone back and made their technologies more accessible.  But there may still be barriers to accessibility that I have not anticipated.  

If you encounter a barrier to participating in this course — even a small inconvenience — please let me know.  Similarly, if you have ideas for making the course more accessible, please share them with me.  

