# (PART) Exploratory Data Analysis (EDA) # {-}

# Waterfalls, Spirals, and Philosophy of Science #

- Waterfall model of development: <https://en.wikipedia.org/wiki/Waterfall_model>
- "The Scientific Method": <https://plato.stanford.edu/entries/scientific-method/#MetMetEndMet>

- Spiral model of development [@BoehmSpiralModelSoftware1988]
- @PengArtDataScience2016 ch. 2 (4-15)
- *[ElliottEpistemicMethodologicalIteration2012?  BrownFunctionalComplexityScientific2015?]*


# EDA as Hunting Phenomena #

- BogenSavingPhenomena1988, §§ intro and III-IV (303-6, 315-25)


# Two EDA Checklists #

- @PengArtDataScience2016 ch. 4 (31-54)
- @HuebnerSystematicApproachInitial2016


# Inspecting Variables #
## Type, range, and missingness ##

- `visdat`
- `skimr`

- Ames housing data

## Constructing aggregates ##
- filter, count, summarize, arrange, view
    - mutate + string operations + functions to parse dollars in NSF data
    - class: NSF Mind and Brain Awards
    - lab: Stanford Open Policing? 

- joins 
    - class: college tuition?
    - lab: covdata


# Visual EDA #
## 1D distributions ##

- categorical: barplot
- numeric: histogram -> density plot -> ecdf

## 2D distributions ##

- categorical x categorical: barplot
- numeric x numeric: scatterplot -> contours
- categorical x numeric: boxplot -> violin plot -> beeswarm

## Multivariate distributions ##

- `ggforce::facet_matrix()`
- lab: correlation heat map + scatterplots
    - geom_text

- upset plots
