project:
  output-dir: _slides

bibliography: book.bib

format: 
  revealjs:
    scrollable: true
    echo: true
    mermaid-format: svg
    css: slides.css
    width: 1440
    height: 1080
    slide-number: true
    execute:
      freeze: auto
